### PR TITLE
Support Rescript attributes in purgecss extractor

### PR DESCRIPTION
**Pull request by lozlow**

### CODE REVIEW

**Comment by dylanirlbeck** [comment]
Hey @lozlow, thanks for the PR! Two things from me:
- Can you give more context around this change? I'm not up to speed with the state of ReScript, so any relevant docs, code snippets, explanations, etc. would help me understand the PR.
- Can you add some tests? You should be able to find them under tests/bucklescript (note that I'm on mobile so I can't remember the exact file). 

Thanks again!

**Comment by lozlow** [comment]
Ah woops I missed those tests! I have added a rescript file and duplicated the test cases in the new rescript file, hope this is okay! Figured it was more likely that the extractor function code would change rather than the test cases in terms of maintenance effort.

In terms of context, rescript changes the syntax for attributes as follows:
ReasonML:
```reason
<div className=[%tw "flex"]>..
```
Rescript:
```rescript
<div className=%tw("flex")>..
```

See more here: https://rescript-lang.org/docs/manual/latest/attribute#extension-point

Thanks for the review!

**Review by dylanirlbeck — APPROVED** [review]
LGTM! Thanks for the quick follow-up.

**Comment by dylanirlbeck** [comment]
@all-contributors please add @lozlow as contributor

**Comment by dylanirlbeck** [comment]
@all-contributors please add @lozlow for code

**Pull request merged**
