### PR TITLE
CI: use npx to call the binary

### PR DESCRIPTION
**Pull request by tatchi**

### CODE REVIEW

**Comment by dylanirlbeck** [comment]
Can you give some more context on why this change is needed?

**Comment by tatchi** [comment]
I have been testing the `ppx` on a windows machine and got an error. I was surprised that it was not caught by the CI. I actually found out that we were not calling the binary correctly (we need to use `ppx`). That's why it was printing nothing on Windows previously:

image

The error was reported in https://github.com/esy/esy/issues/1160#issue-688022785 and using `esy 0.6.4` fixes it.

* First commit use `npx` to call the binary -> you can see the error on windows
* Second commit switch to `esy@0.6.4` -> no more error and the result of the binary is correctly printed

**Comment by ManasJayanth** [comment]
@dylanirlbeck Following up from the issue at  esy/esy#1160 , what happened was esy incorrectly assumed `rewritePrefix` is true. Explicitly setting `rewritePrefix` to true in the esy.json can avoid this problem and still continue the use of 0.6.6.

To give some more context:  rewritePrefix is alpha quality feature. It was earlier made opt-in in the earliers releases, but recently the rewriting behaviour has seen improvements. We would prefix if more users opt into using it and providing feedback.

**Comment by dylanirlbeck** [comment]
@ManasJayanth Awesome, thanks for the explanation.

**Pull request merged**
