### PR TITLE
CI: try to fix windows build 

### PR DESCRIPTION
**Pull request by tatchi**
I didn't add `windows` to the `release` script because I' m not sure how to test that ^^

### CODE REVIEW

**Comment by dylanirlbeck** [comment]
Hi @tatchi ! Thanks for the PR, I saw your messages in Discord and was also working on getting a stable Windows release to work: https://github.com/dylanirlbeck/tailwind-ppx/pull/33.

What I'm curious about (and maybe you can provide some insight), is why one would choose OCaml 4.06.0 vs 4.06.1? I would love to understand the tradeoffs before making this change, since I've seen other PPXs use 4.06.1000 in their ocaml version.

**Comment by tatchi** [comment]
I've never developed any `ppx` so I don't know which OCaml version is the best to use in this case.

But actually I set the version to `~4.06.0` which means that all versions `4.06.x` are valid. When there's no `esy.lock` yet, I guess that `esy` will install the latest version corresponding to this `semver` (like `yarn` or `npm` does).

If you look at the `esy.lock` file, the `ocaml@4.6.1000` version seems to be the version used:

```js
    "ocaml@4.6.1000@d41d8cd9": {
      "id": "ocaml@4.6.1000@d41d8cd9",
      "name": "ocaml",
      "version": "4.6.1000",
      "source": {
        "type": "install",
        "source": [
          "archive:https://registry.npmjs.org/ocaml/-/ocaml-4.6.1000.tgz#sha1:99525ef559353481396454f9a072dedc96b52f44"
        ]
      },
      "overrides": [],
      "dependencies": [],
      "devDependencies": []
    },
```

**Comment by tatchi** [comment]
If you prefer, I think there would be no issue to fix the version to `4.6.1000` :)

**Comment by dylanirlbeck** [comment]
Awesome, that makes sense. Can you try to fix the version to 4.6.1000 and see if it passes for Windows on CI (and works locally)? If not, we can definitely keep it at `~4.6.0`. 

On a side note, it looks like the native tests on windows are failing at the `Export dependencies` step. We might not need this step, so I'll investigate.

**Comment by tatchi** [comment]
> On a side note, it looks like the native tests on windows are failing at the `Export dependencies` step. We might not need this step, so I'll investigate.

Yes, I don't know why but there's a `Permission Denied`. Indeed, I'm not sure either that this step makes sense anyway ^^

**Comment by dylanirlbeck** [comment]
@tatchi So it looks like this CI flow (which I stole from the default `spin` setup) uses the `esy export-dependencies` command for caching purposes during CI. If the Windows build continues to fail we should separate out windows into a separate CI check and just omit the export/caching. I can do this or if you want to include it in your PR that'd be awesome too.

Here's the docs for the command: https://esy.sh/docs/en/commands.html#esy-export-dependencies

**Comment by tatchi** [comment]
> @tatchi So it looks like this CI flow (which I stole from the default `spin` setup) uses the `esy export-dependencies` command for caching purposes during CI. If the Windows build continues to fail we should separate out Windows into a separate CI check and just omit the export/caching. I can do this or if you want to include it in your PR that'd be awesome too.
> 
> Here's the docs for the command: https://esy.sh/docs/en/commands.html#esy-export-dependencies

Let's skip this step for now on windows. It might be good also to try out the config from `hello-reason` repo: https://github.com/esy-ocaml/hello-reason/blob/master/.github/workflows/build.yml

**Comment by dylanirlbeck** [comment]
Nice, tests passed! I'm going to go ahead and merge this in, and then I'll get Windows working in the release workflow. 

Thanks again @tatchi !

**Pull request merged**
