### PR TITLE
use ocaml-css-parser lib

### LINKED ISSUE #87: Update OCaml version to 4.10
Based on this post - https://reasonml.chat/t/ppx-no-need-for-separate-ppx-and-ppx6-with-ocaml-migrate-parsetree-1-6-0/2210 - it seems we can bump the version of OCaml to 4.10 while still preserving backwards compatibility with the current version of BuckleScript.

This would also allow us to use the css-parser dependency from OPAM, instead of duplicating the code (#80)

cc @tatchi for your thoughts

### PR DESCRIPTION
**Pull request by tatchi**
Fixes #87 

I was finally able to use a higher version of OCaml (4.9.1) and still have errors formatted properly as before (thanks to @jchavarri). The trick was to use the `--embed-errors` option.

There's still a native test which fails I'm not sure why...

~Note: this PR is blocked by https://github.com/astrada/ocaml-css-parser/pull/6~

### CODE REVIEW

**Comment by dylanirlbeck** [comment]
@tatchi Nice!!! I'll review this soon, I'm super excited to up the OCaml version.

**Comment by tatchi** [comment]
> EDIT: I think I know which test is failing --- see the fix I implemented for #89 . Those changes are not upstream in `css-parser`, so using that as a dependency is breaking the test. I'll try to get the upstream PR merged in ASAP so a new version of `css-parser` can be published.

Cool, let's wait for a new release of `css-parser` then :)

**Comment by tatchi** [comment]
@dylanirlbeck I bumped `css-parser` to the latest version `0.2.4` but the test still fails... Do you have any idea what might be the cause?

**Comment by tatchi** [comment]
I think the error comes from the comparison of the `Location.Error` exception. For now I changed the assertion to just make sure that an exception is thrown.

**Comment by tatchi** [comment]
@dylanirlbeck it builds now on windows but CI fails at a later stage: `Get Esy UsePpx binary path`. Any idea what might go wrong here?

**Comment by dylanirlbeck** [comment]
@tatchi Hmm I'm a bit lost on this one, especially because the test passes on Linux/Mac. I'll continue to investigate.. sorry for the delay on this, just started a new job haha

**Comment by dylanirlbeck** [comment]
@tatchi So I'm still stuck on this, and have posted on Discord in hopes of getting a response. What causes even more confusion is the fact that the same test passes in [this PR](https://github.com/dylanirlbeck/tailwind-ppx/pull/97/checks?check_run_id=732768019), with the only difference between the two PRs being yours changes the OCaml version. 

I'm very much confused..

**Comment by dylanirlbeck** [comment]
@tatchi See https://github.com/esy/esy/issues/1096#issuecomment-643652552. Can you try the fix proposed in the comments by Manas?

**Comment by tatchi** [comment]
@dylanirlbeck looks like it fixes the issue :)

**Comment by dylanirlbeck** [comment]
@tatchi 🔥 🔥 🔥 

I'm going to double-check to see if a new esy version is on the horizon, since I'm not sure if using the nightly build is super reliable -- just hang tight, I'll merge this in either way by the end of the week.

**Comment by tatchi** [comment]
> @tatchi 🔥 🔥 🔥
> 
> I'm going to double-check to see if a new esy version is on the horizon, since I'm not sure if using the nightly build is super reliable -- just hang tight, I'll merge this in either way by the end of the week.

Nice :) Not sure what are you plan about #100 but once this one is merged, I can rebase #100 and there won't be any needs for nightly version of esy

**Comment by tatchi** [comment]
@dylanirlbeck esy 0.6.5 was just released so I switched back to the latest version (not the nightly one). I guess it should be ok :)

**Pull request merged**
